### ISSUE TITLE
Latest version of yangsuite has --https option so ngnx is no longer needed.

### ISSUE THREAD

**Issue by miott** [CiscoTestAutomation/yang#106]
The ``yangsuite --https`` option will activate https in the internal web server.  The docker-compose implementation should take advantage of that option and remove the nginx container as a requirement.

**Comment by kameswararaot** [comment]
Hi miott,

Could you please provide some more information? if possible can you share me the logs or traceback?

**Comment by miott** [comment]
Added this issue to wrong repository.
