### ISSUE TITLE
Need documentation added for gnmi feature.

### ISSUE THREAD

**Issue by miott** [CiscoTestAutomation/yang#11]
A gnmi.py module was added containing a new Gnmi class.  The usage for this class is well documented in the docstrings of the module but this needs to be added to connector documentation.

**Comment by jeaubin** [comment]
Was this addressed   yes right ?

**Comment by miott** [comment]
Not yet.

**Comment by tahigash** [comment]
@miott no doc for gNMI for a long time. can I ask you to plan adding the doc?

**Comment by miott** [comment]
@yuekyang , can you build the docs in https://readthedocs.org/projects/yangconnector/.  I don't have permission.  If you want to give me permission I can do it.

**Comment by miott** [comment]
API documentation for Gnmi class can be found here: https://developer.cisco.com/docs/yang-connector/.  All the documentation is hosted at https://developer.cisco.com/docs/.  I do not know the process for getting the docs published at that site but they are up-to-date for Gnmi class.
