### ISSUE TITLE
NETCONF does not work with EnXR simulator as target test device.

### ISSUE THREAD

**Issue by miott** [CiscoTestAutomation/yang#12]
EnXR simulator communicates through Unix sockets instead of a network connection.  The pyATS Unicon library works with CLI connections but not NETCONF and gNMI.

**Comment by jeaubin** [comment]
@miott   was this addressed by your work ?

**Comment by miott** [comment]
> @miott was this addressed by your work ?

The enxr did not have a plugin for unicon so I will change the description above.

I have a contractor that implemented the enxr into the unicon library but he ran into an issue with the pyats install.

Background:
The enxr simulator is built using an XR workspace on an ADS.  This simulator, when activated, manipulates linux mounts to give the ADS the structure similar to the internal structure of an XR device.
To make it work with YANG Suite, the user has to install YANG Suite into the XR workspace.

When he installs pyats into the XR workspace using the /auto/pyats/bin/pyats install command and activating it using env.sh, this symlink is a problem:
```
lrwxrwxrwx. 1 miott eng     7 Jun  1 08:41 python -> python3
lrwxrwxrwx. 1 miott eng    43 Jun  1 08:41 python3 -> /auto/pysw/cel7x/python64/3.6.4/bin/python3
```
He removed the symlink and pointed to a local copy of python3.6 and it worked.  I told him to look at the pyats install options. I think this one will work.
```
Python Options:
  --py-home             Python binary location. Use this to provide an alternative Python binary to
                        create this pyATS virtual environment with.
```
Should be a pull request soon in unicon.plugins for this work.

I told him to look into creating a unicon.plugin for netconf.  Any reason why we have a separate library, yang.connector, to handle netconf?

**Comment by miott** [comment]
@ashojosh added NetconfEnxr class 12/2020 but it is broken with error:
``TRACEBACK: 'NetconfEnxr' object has no attribute 'send_cmd'``

**Comment by tahigash** [comment]
@miott any update on this...?

**Comment by miott** [comment]
We have not received a request to add gnmi to EnXR simulator so netconf is sufficient.
