### ISSUE TITLE
breakage seen with newly released pyats v19.5 packages

### ISSUE THREAD

**Issue by mdear** [CiscoTestAutomation/yang#2]
yang.connector is not handling the case where self.connectioninfo now contains the "credentials" member.  The credentials feature was released as part of pyATS v19.5.

$ pip list
Package              Version   
-------------------- ----------
asn1crypto           0.24.0    
asyncssh             1.16.1    
bcrypt               3.1.4     
certifi              2018.10.15
cffi                 1.11.5    
chardet              3.0.4     
cryptography         2.6.1     
defusedxml           0.5.0     
dill                 0.2.9     
distro               1.4.0     
httplib2             0.11.3    
idna                 2.7       
Jinja2               2.10      
jira                 2.0.0     
junit-xml            1.8       
lxml                 4.2.5     
MarkupSafe           1.1.0     
ncclient             0.5.3     
netconf-console      2.1.1     
oauthlib             3.0.1     
paramiko             2.4.2     
pathspec             0.5.9     
pbr                  5.1.3     
pexpect              4.7.0     
pip                  19.1.1    
psutil               5.4.8     
ptyprocess           0.6.0     
pyasn1               0.4.4     
pyats                19.5.0    
pyats.aereport       19.5.0    
pyats.aetest         19.5.0    
pyats.async          19.5.0    
pyats.connections    19.5.0    
pyats.datastructures 19.5.0    
pyats.easypy         19.5.0    
pyats.examples       19.5.0    
pyats.kleenex        19.5.0    
pyats.log            19.5.0    
pyats.results        19.5.0    
pyats.tcl            19.5.0    
pyats.templates      19.5.0    
pyats.topology       19.5.0    
pyats.utils          19.5.0    
pycparser            2.19      
PyJWT                1.7.1     
PyNaCl               1.3.0     
PyYAML               3.13      
requests             2.20.0    
requests-oauthlib    1.2.0     
requests-toolbelt    0.9.1     
setproctitle         1.1.10    
setuptools           39.0.1    
six                  1.11.0    
unicon               19.5.0    
urllib3              1.24.1    
xmltodict            0.11.0    
yamllint             1.15.0    
yang.connector       3.0.0     
(pyats) MBERETTA-M-K1L8:~ mberetta$ cat svo/temp/svo_100.yaml
devices:
  ncs:
    type: nso
    os: linux
    tacacs:
      username: admin
    passwords:
      tacacs: admin
      enable: admin
      line: admin
    connections:
      defaults:
        class: 'unicon.Unicon'
        via: netconf
      admin:
        protocol: https
        ip: 10.58.228.93
        port: 8443
        username: CISCO15
        password: otbu+2019
      host:
        protocol: ssh
        ip: 10.58.228.93
        port: 22
        username: root
        password: lablab
      netconf:
        class: yang.connector.Netconf
        ip : 10.58.228.100
        port: 830
        username: CISCO15
        password: otbu+2019
        hostkey_verify: False
        look_for_keys: False
        timeout: 120
    custom:
      host_type: Card
(pyats) MBERETTA-M-K1L8:~ mberetta$ 
(pyats) MBERETTA-M-K1L8:~ mberetta$ 
(pyats) MBERETTA-M-K1L8:~ mberetta$ python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ats.topology import loader
>>> testbed = loader.load('svo/temp/svo_100.yaml')
>>> svo = testbed.devices['ncs']
>>> svo.connect(via='netconf')
/Users/mberetta/pyats/lib/python3.6/site-packages/paramiko/ecdsakey.py:164: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.ecdsa_curve.curve_class(), pointinfo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyats/connections/manager.py", line 305, in pyats.connections.manager.ConnectionManager.connect
  File "/Users/mberetta/pyats/lib/python3.6/site-packages/yang/connector/__init__.py", line 324, in connect
    self.session.connect(**defaults)
TypeError: connect() got an unexpected keyword argument 'credentials'
>>>

**Comment by siming85** [comment]
fixed in commit #5ad52c6
