### ISSUE TITLE
Stabilize version requirements

### ISSUE THREAD

**Issue by miott** [CiscoTestAutomation/yang#41]
Hitting version requirement issue (again) mainly with regard to ``grpcio``.  Previously yang.connector was ``grpcio<=1.28.1`` and my library requires yang.connector so getting version conflict again.  Can you explain why grpcio is restricted to less than 1.36.1 in yang.connector now?  I control ``cisco-gnmi`` and grpcio is required there and open to any version.

yang.connector:

```
    # package dependencies
    install_requires =  [
        'paramiko >= 1.15.1',
        'lxml >= 3.3.0',
        'ncclient >= 0.6.6, < 0.6.10',
        'grpcio <= 1.36.1',
        'cisco-gnmi >= 1.0.13, < 2.0.0',
    ],
```
yang.ncdiff:

yang.ncdiff uses cisco-gnmi.proto now so ``yang/ncdiff/src/yang/ncdiff/proto/*`` modules are no longer needed.  The ``proto`` is installed from ``grpcio``.  I switched yang.ncdiff to using cisco-gnmi.proto because I wanted yang.connector and yang.ncdiff to use the same "proto".  On another note, why does ncdiff require ``yang.connector >= 3.0.0``?
```
    install_requires =  [
        'pyang >= 1.7.3',
        'ncclient >= 0.6.3, < 0.6.10',
        'requests >= 2.18.4',
        'cisco-gnmi',
        'xmljson >= 0.1.9',
        'yang.connector >= 3.0.0',
    ],
```
The best solution going forward would be to remove ``grpcio`` from the yang.connector setup.py requirement.

**Comment by tahigash** [comment]
@yuekyang any chance to look into this?

**Comment by oboehmer** [comment]
We are also hitting an `ncclient` requirement issue in radkit requiring `ncclient>=0.6.12` conflicting with yang.connector's `>= 0.6.3, < 0.6.10`. Can you help?

**Comment by dwapstra** [comment]
I have updated the version pinning via this PR https://github.com/CiscoTestAutomation/yang/pull/64
