### ISSUE TITLE
RESTCONF support?

### ISSUE THREAD

**Issue by andy-maier** [CiscoTestAutomation/yang#70]
Is there a plan to add support for the RESTCONF protocol?
Are there other python packages that support YANG with RESTCONF?

**Comment by ademz** [comment]
Yes you can use the `RESTCONF` protocol with PyATS. Please check the links below. 

- https://github.com/CiscoTestAutomation/solutions_examples/tree/master/blitz_cli_rest_netconf_gnmi
- https://yangncdiff.readthedocs.io/en/latest/README.html
- https://yangncdiff.readthedocs.io/en/latest/usage_rc_get.html

Thanks,
Adem Oztas
