### ISSUE TITLE
yang_snapshot_restore causes traceback using NetconfEnxr class.

### ISSUE THREAD

**Issue by miott** [CiscoTestAutomation/yang#85]
yang_snapshot_restore is accessing a ``locked`` member in the NetconfEnxr class that does not exist.

<img width="1608" alt="Screenshot 2023-04-05 at 9 23 51 PM" src="https://user-images.githubusercontent.com/2295386/230186600-84a10a4b-5540-400a-a14a-e75d5be48fcb.png">

**Comment by yuekyang** [comment]
May I access the complete log? I'd like to understand this `NetconfEnxr` object more.

**Comment by miott** [comment]
#86 fixes this issue.  Need approval for merge.
