### ISSUE TITLE
Add yang.verifiers documentation to developer.cisco.com.

### ISSUE THREAD

**Issue by miott** [CiscoTestAutomation/yang#96]
The [yang.connector](https://github.com/CiscoTestAutomation/yang/tree/master/connector) docs are published at https://developer.cisco.com/docs/yang-connector/.  The new YANG verifier feature, [yang.verifiers](https://github.com/CiscoTestAutomation/yang/tree/master/verifiers/), should also have documentation published at https://developer.cisco.com/docs/yang-verifiers/.

**Comment by SohanTirpude** [comment]
Hello @miott,

I will be working on this ticket. Kindly let me check with the team on this and I'll update you soon on this.

**Comment by SohanTirpude** [comment]
Hello @miott,

We have added this to our backlog and soon we'll be working on this. Thank you.
